<h1 class="text-center mt-3 mb-5">Articles</h1>

<a href="http://blogoc/?page=post&action=create"
    class="btn btn-success d-block mb-2">
    Create a new post
</a>

<table class="table table-dark table-striped table-hover">
    <thead>
        <th>id</th>
        <th>id auteur</th>
        <th>statut</th>
        <th>titre</th>
        <th>slug</th>
        <th>change statut</th>
        <th>supprimer</th>
    </thead>

    <tbody>
        <?php foreach($posts as $post){ 
            $postId = $post->getId();
            $authorId = $post->getAuthorId();
            $status = $post->getStatus();
        ?>
        <tr>
            <td>
                <a href="http://blogoc/?page=post&action=show&id=<?= $postId ?>"
                   class="link-info text-decoration-none">
                    <?= $postId ?>
                </a>
            </td>
            <td>
                <a href="http://blogoc/?page=user&action=show&id=<?= $authorId ?>"
                   class="link-primary text-decoration-none">
                    <?= $authorId ?>
                </a>
            </td>
            <td class="text-<?php 
                    if($status === 'online'){ echo 'info';}
                    else{ echo 'warning';}
                ?>">
                <?= ucfirst($status) ?>             
            </td>
            <td><?= $post->getTitle(); ?></td>
            <td><?= $post->getSlug(); ?></td>
            <td>
                <?php if($status === 'draft'){ ?>
                    <a href="http://blogoc/?page=post&action=updateStatus&id=<?= $postId ?>" class="btn btn-info d-block">online</a>
                <?php }else{ ?>
                    <a href="http://blogoc/?page=post&action=updateStatus&id=<?= $postId ?>" class="btn btn-warning d-block">draft</a>
                <?php } ?>
            </td>
            <td>
                <a href="http://blogoc/?page=post&action=delete&id=<?= $postId ?>" class="btn btn-danger d-block">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>  