<h1 class="text-center mt-3 mb-5">Users</h1>
<table class="table table-dark table-striped table-hover">
    <thead>
        <th>id</th>
        <th>role</th>
        <th>pseudo</th>
        <th>email</th>
        <th>change role</th>
        <th>supprimer</th>
    </thead>

    <?php foreach($users as $user){ ?>
        <tr>
            <td>
                <a href="http://blogoc/?page=user&action=show&id=<?= $user->getId(); ?>"
                    class="link-info text-decoration-none">
                    <?= $user->getId(); ?>
                </a>
            </td>
            <td class="text-<?php
                    if($user->getRole() === 'admin'){ echo 'success';}
                    else{ echo 'primary';}
                ?>">
                <?= ucfirst($user->getRole()) ?>           
            </td>
            <td><?= $user->getPseudo(); ?></td>
            <td><?= $user->getMail(); ?></td>
            <td>
                <?php if($user->getRole() === 'user'){ ?>
                    <a href="http://blogoc/?page=user&action=update&id=<?= $user->getId() ?>" class="btn btn-success d-block">admin</a>
                <?php }else{ ?>
                    <a href="http://blogoc/?page=user&action=update&id=<?= $user->getId() ?>" class="btn btn-primary d-block">user</a>
                <?php } ?>
            </td>
            <td>
                <a href="http://blogoc/?page=user&action=delete&id=<?= $user->getId() ?>" class="btn btn-danger d-block">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
    <?php } ?>
</table>