<?php

use App\Entity\PostEntity;
?>
<h1 class="text-center mt-3 mb-5">Create a new post</h1>

<form method="post">
    <div class="mb-2">
        <label for="title" class="form-label">Title :</label>
        <input type="text" name="title" class="form-control" placeholder="Title">
    </div>

    <div class="mb-2">
        <label for="status" class="form-label">Status :</label>
        <select name="status" class="form-select">
            <option value="<?= PostEntity::STATUS_DRAFT ?>"><?= ucfirst(PostEntity::STATUS_DRAFT) ?></option>
            <option value="<?= PostEntity::STATUS_ONLINE ?>"><?= ucfirst(PostEntity::STATUS_ONLINE) ?></option>
        </select>
    </div>

    <div class="mb-2">
        <label for="content" class="form-label">Votre mot de passe :</label>
        <textarea name="content" class="form-control" style="height: 100px" placeholder="Write content..."></textarea>
    </div>

    <button type="submit" class="btn btn-success">Create</button>
</form>