<h1 class="text-center mt-3 mb-5">Requena Guillaume</h1>

<p class="text-center">
    <img src="assets/img/logo.png" alt="logo de blogOC">
</p>

<p class="text-center fst-italic">Guillaume Requena, le développeur qui à déjà du boulot !</p>

<div class="d-flex justify-content-evenly">
    <section class="text-center mb-5">
        <h2 class="mb-3 mt-3">CV</h2>
        <a href="assets/pdf/cv.pdf" class="btn btn-danger" target="_blank">
            PDF
        </a>        
        <a href="https://requenaguillaume.github.io/" class="btn btn-success" target="_blank">
            Online
        </a>        
    </section>
    
    <section class="text-center mb-5">
        <h2 class="mb-3 mt-3">Social</h2>
        <?php require 'src/template/partial/social.phtml'; ?>
    </section>
</div>

<div class="d-flex justify-content-center">
    <section class="w-50">
        <h2>Contact</h2>
        <form method="post">
            <div class="mb-2">
                <label for="lastName" class="form-label">Your Last name :</label>
                <input type="text" name="lastName" class="form-control" placeholder="Last Name">
            </div>
        
            <div class="mb-2">
                <label for="firstName" class="form-label">Your First name :</label>
                <input type="text" name="firstName" class="form-control" placeholder="First Name">
            </div>
        
            <div class="mb-2">
                <label for="email" class="form-label">Your Email :</label>
                <input type="email" name="email" class="form-control" placeholder="Email">
            </div>
        
            <div class="mb-2">
                <label for="content" class="form-label">Your message :</label>
                <textarea name="content" class="form-control" style="height: 100px" placeholder="Write content..."></textarea>
            </div>
        
            <button type="submit" class="btn btn-success w-100">Envoyer</button>
        </form>
    </section>
</div>