<h1>LOGIN TEMPLATE</h1>
    
<form method="post">
    <div class="mb-2">
        <label for="email" class="form-label">Votre adresse e-mail :</label>
        <input type="email" name="email" class="form-control" placeholder="Email">
    </div>

    <div class="mb-2">
        <label for="pass" class="form-label">Votre mot de passe :</label>
        <input type="password" name="pass" class="form-control" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-success">S'inscrire</button>
</form>