<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Blog OC - Contact</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
            crossorigin="anonymous"
        />
    </head>
    <body>
        <main class="container">
            <h1><?= $data['fullName'] ?> contacted you</h1>
            <h2>Email : <?= $data['email'] ?></h2>
            <?php if($data['userId']){ echo "<h3>User id : {$data['userId']}</h3>"; } ?>
            <p>
                Saying : 
                <br>
                <?= $data['content'] ?>
            </p>
        </main>
    </body>
</html>