<h1>REGISTER TEMPLATE</h1>

<form method="post">
    <div class="mb-2">
        <label for="pseudo" class="form-label">Choisissez votre pseudo :</label>
        <input type="text" name="pseudo" class="form-control" placeholder="Pseudo">
    </div>

    <div class="mb-2">
        <label for="email" class="form-label">Votre adresse e-mail :</label>
        <input type="email" name="email" class="form-control" placeholder="Email">
    </div>

    <div class="mb-2">
        <label for="pass" class="form-label">Votre mot de passe :</label>
        <input type="password" name="pass" class="form-control" placeholder="Password">
    </div>

    <div class="mb-2">
        <label for="verifpass" class="form-label">Retapez votre mot de passe :</label>
        <input type="password" name="verifpass" class="form-control" placeholder="Password again">
    </div>

    <button type="submit" class="btn btn-success">S'inscrire</button>
</form>