<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta
        name="description"
        content=""
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog OC</title>
    <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
        type="text/css"
    />
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
        crossorigin="anonymous"
      />
    <!-- <link rel="shortcut icon" href="./assets/img/logo.png" type="image/png"/> -->
  </head>
  <body>

    <?php 

        require 'src/template/partial/header.phtml';

        echo '<main class="bg-primary">Test Main</main>'; // test bootstrap OK

        require 'src/template/partial/footer.phtml';

    ?>

    <script type="module" src="assets/js/main.js"></script>
  </body>
</html>