<footer class="text-center text-white bg-dark">
    <div class="container">
        <section class="mt-5">
            <div class="row text-center d-flex justify-content-center pt-5">
                <?php if($this->getUser() && $this->getUser()->getRole() === 'admin'){ ?> 
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a class="nav-link text-light" href="http://blogoc/?page=admin">Admin</a>
                        </h6>
                    </div>

                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a class="nav-link text-light" href="http://blogoc/?page=user&action=list">Users</a>
                        </h6>
                    </div>

                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a class="nav-link text-light" href="http://blogoc/?page=post&action=list">Posts</a>
                        </h6>
                    </div>

                    <div class="col-md-2">                       
                        <h6 class="text-uppercase font-weight-bold">
                            <a class="nav-link text-light" href="http://blogoc/?page=post&action=create">New post</a>
                        </h6>
                    </div>

                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a class="nav-link text-light" href="http://blogoc/?page=comment&action=list">Comments</a>
                        </h6>
                    </div>
                <?php } ?>
            </div>
        </section>

        <section class="text-center mb-5 mt-5">
            <?php require 'src/template/partial/social.phtml'; ?>
        </section>
    </div>

    <hr/>

    <div class="text-center p-3 bg-dark">
        <p>© 2023 Copyright blogOC</p>
    </div>
</footer>