<header class="mb-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="http://blogoc/?page=homepage">Home</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" href="http://blogoc/?page=post">Posts</a>
                    </li>
                    <?php if($this->getUser() && $this->getUser()->getRole() === 'admin'){ ?>                        
                        <li class="nav-item">
                            <a class="nav-link text-light" href="http://blogoc/?page=post&action=create">New post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="http://blogoc/?page=admin">Admin</a>
                        </li>
                    <?php }
                        if($this->getUser()){ 
                    ?>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="http://blogoc/?page=user">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger text-light ms-2" href="http://blogoc/?page=logout">Logout</a>
                        </li>
                    <?php }else{ ?>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success text-light ms-2" href="http://blogoc/?page=login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-light ms-2" href="http://blogoc/?page=user&action=create">Register</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </nav>
</header>