<header class="mb-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="http://blogoc/?page=homepage">Home</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" href="http://blogoc/?page=post">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="#">Profil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="http://blogoc/?page=admin">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-success text-light" href="http://blogoc/?page=login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-danger text-light" href="http://blogoc/?page=logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary text-light" href="http://blogoc/?page=register">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>